### ISSUE TITLE
Typo in $rules

### ISSUE THREAD

**Issue by Erroneuz** [junecastillote/Export-ExoMailForwardRules#1]
Just a heads-up
`$rules = Get-InboxRule -Mailbox $mailbox.UserPrincipalname | Select-Object Name, Description, Enabled, Priority, ForwardTo, ForwardAsAttachmentTo, RedirectTo, DeleteMessage | Where-Object {($_.ForwardTo -ne $null) -or ($_.ForwardAsAttachmentTo -ne $null) -or ($_.RedirectsTo -ne $null)}`

Has a small typo `($_.RedirectsTo -ne $null)` should be `($_.RedirectTo -ne $null)`

**Comment by junecastillote** [comment]
Thanks. I'll get this fixed.

**Comment by junecastillote** [comment]
This is fixed in v1.1
